name: Create Github Release
on:
  push:
    branches:
      - main

jobs:
  createRelease:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tag.outputs.tag_name }}
          name: v${{ steps.tag.outputs.tag_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
